 
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: silent
external-controller: '127.0.0.1:9090'

proxies:
  - name: "Outline-旧金山"
    type: ss
    server: 
    port: 25292
    cipher: chacha20-ietf-poly1305
    password: ""
    udp: true

proxy-providers:
  Luna:
    type: http
    url: &tag=clash
    filter: "Hong|Taiwan|Japan|Singapore|United States"
    interval: 3600
    path: ./providers/proxy-Luna.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  # Guolicheng:
  #   type: http
  #   url: &tag=clash
  #   filter: "港|台|日|新|美"
  #   interval: 3600
  #   path: ./providers/proxy-Guolicheng.yaml
  #   health-check:
  #     enable: true
  #     url: http://www.gstatic.com/generate_204
  #     interval: 300

  守候:
    type: http
    url: &tag=clash
    exclude-filter: "KR|100x"
    interval: 3600
    path: ./providers/proxy-Shouhou.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

# filter: '(.*0\.2x|.*0\.01x)'
proxy-groups:
  - { name: '手动切换', type: select, proxies: [Outline-旧金山], use: [Luna, 守候], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png"}
  - { name: '守候影院', type: select, use: [守候], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Media.png"}
  - { name: '谷歌服务', type: select, proxies: [日本节点, 香港节点, 新加坡节点, 台湾节点, 美国节点, 手动切换, DIRECT], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png"}
  - { name: 'Youtube', type: select, proxies: [日本节点, 香港节点, 新加坡节点, 台湾节点, 美国节点, 手动切换, DIRECT], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png"}
  - { name: '人工智能', type: select, proxies: [手动切换, DIRECT], use: [守候], filter: '(?!.*0\.01x)(?!.*100x)(?!.*HK)(?=.*(JP|US|TW|SG))', icon: "https://raw.githubusercontent.com/Toperlock/Quantumult/main/icon/ChatGPT.png"}
  - { name: 'Netflix', type: select, proxies: [日本节点, 香港节点, 新加坡节点, 台湾节点, 美国节点, 手动切换, DIRECT], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png"}
  - { name: '国外网站', type: select, proxies: [日本节点, 香港节点, 新加坡节点, 台湾节点, 美国节点, 手动切换, DIRECT], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png"}
  - { name: 'Paypal', type: select, proxies: [Outline-旧金山, 美国节点, 手动切换, DIRECT], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/PayPal.png"}
  - { name: 'Telegram', type: select, proxies: [日本节点, 香港节点, 新加坡节点, 台湾节点, 美国节点, 手动切换, DIRECT], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png"}
  - { name: 'Twitter', type: select, proxies: [日本节点, 香港节点, 新加坡节点, 台湾节点, 美国节点, 手动切换, DIRECT], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Twitter.png"}
  - { name: 'Spotify', type: select, proxies: [日本节点, 香港节点, 新加坡节点, 台湾节点, 美国节点, 手动切换, DIRECT], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Spotify.png"}
  - { name: '苹果服务', type: select, proxies: [日本节点, 香港节点, 新加坡节点, 台湾节点, 美国节点, 手动切换, DIRECT], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png"}
  - { name: 'Google Voice', type: select, proxies: [Outline-旧金山, 美国节点, 手动切换, DIRECT], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google.png"}
  - { name: '微软服务', type: select, proxies: [日本节点, 香港节点, 新加坡节点, 台湾节点, 美国节点, 手动切换, DIRECT], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png"}
  - { name: '兜底分流', type: select, proxies: [日本节点, 香港节点, 新加坡节点, 台湾节点, 美国节点, 手动切换, DIRECT], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color//Final.png"}
  - { name: '广告拦截', type: select, proxies: ['REJECT'], icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Advertising.png"}
  - { name: '全球直连', type: select, proxies: ['DIRECT'], icon: "https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Direct.png"}

  - { name: '香港节点', type: url-test, use: [Luna, 守候], filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|美)).)*$", interval: 300, icon: "https://raw.githubusercontent.com/Orz-3/mini/master/Color/HK.png"}
  - { name: '台湾节点', type: url-test, use: [Luna, 守候], filter: "(?=.*(台|TW|(?i)Taiwan))^((?!(港|日|韩|新|美)).)*$", interval: 300, icon: "https://raw.githubusercontent.com/Orz-3/mini/master/Color/TW.png"}
  - { name: '日本节点', type: url-test, use: [Luna, 守候], filter: "(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$", interval: 300, icon: "https://raw.githubusercontent.com/Orz-3/mini/master/Color/JP.png"}
  - { name: '新加坡节点', type: select, use: [Luna, 守候], filter: "(?=.*(新|狮|獅|SG|(?i)Singapore))^((?!(港|台|日|韩|兰|美)).)*$", interval: 300, icon: "https://raw.githubusercontent.com/Orz-3/mini/master/Color/SG.png"}
  - { name: '美国节点', type: url-test, use: [Luna, 守候], filter: "(?=.*(美|US|(?i)States|American))^((?!(港|台|日|韩|新)).)*$", interval: 300, icon: "https://raw.githubusercontent.com/Orz-3/mini/master/Color/US.png"}

rules:
  - DOMAIN-SUFFIX,congblog.top,手动切换
  - DOMAIN-SUFFIX,cn2gias.uk,守候影院
  - DOMAIN-SUFFIX,raw.githubusercontent.com,国外网站
  - DOMAIN-SUFFIX,bing.com,国外网站
  - DOMAIN-SUFFIX,bingapis.com,国外网站
  - PROCESS-NAME,ArcGISPro,DIRECT
  - RULE-SET,google,谷歌服务
  - RULE-SET,Google,谷歌服务
  - RULE-SET,telegramcidr,手动切换
  - RULE-SET,Microsoft,微软服务
  - DOMAIN-SUFFIX,openai.com,人工智能
  - DOMAIN-SUFFIX,chatgpt.com,人工智能
  - DOMAIN-KEYWORD,felo.ai,人工智能
  - DOMAIN-SUFFIX,chatgpt4google.com,人工智能
  - DOMAIN-SUFFIX,glarityapi.com,人工智能
  - RULE-SET,AI,人工智能
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Paypal,Paypal
  - RULE-SET,Twitter,Twitter
  - RULE-SET,Spotify,Spotify
  - RULE-SET,Google Voice,Google Voice
  - DOMAIN-SUFFIX,o3o.ca,国外网站
  - DOMAIN-SUFFIX,siji.typlog.io,国外网站
  - DOMAIN-SUFFIX,gateway.icloud.com,DIRECT
  - DOMAIN-SUFFIX,proton.me,国外网站
  - DOMAIN-SUFFIX,i.ytimg.com,国外网站
  - DOMAIN-KEYWORD,obsidian,DIRECT
  - DOMAIN-KEYWORD,undefapp,国外网站
  - DOMAIN-KEYWORD,digitalocean,国外网站
  - DOMAIN-SUFFIX,podcasts.apple.com,手动切换
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,Backlist,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,youtube,Youtube
  - DOMAIN-KEYWORD,youtube,Youtube
  - DOMAIN,youtubei.googleapis.com,Youtube
  - DOMAIN,yt3.ggpht.com,Youtube
  - DOMAIN-SUFFIX,googlevideo.com,Youtube
  - DOMAIN-SUFFIX,gvt2.com,Youtube
  - DOMAIN-SUFFIX,withyoutube.com,Youtube
  - DOMAIN-SUFFIX,youtu.be,Youtube
  - DOMAIN-SUFFIX,youtube-nocookie.com,Youtube
  - DOMAIN-SUFFIX,youtube.com,Youtube
  - DOMAIN-SUFFIX,youtubeeducation.com,Youtube
  - DOMAIN-SUFFIX,youtubegaming.com,Youtube
  - DOMAIN-SUFFIX,youtubekids.com,Youtube
  - DOMAIN-SUFFIX,yt.be,Youtube
  - DOMAIN-SUFFIX,ytimg.com,Youtube
  - DOMAIN-KEYWORD,netflixdnstest,Netflix
  - DOMAIN,netflix.com.edgesuite.net,Netflix
  - DOMAIN-SUFFIX,fast.com,Netflix
  - DOMAIN-SUFFIX,netflix.com,Netflix
  - DOMAIN-SUFFIX,netflix.net,Netflix
  - DOMAIN-SUFFIX,netflixdnstest0.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest1.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest2.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest3.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest4.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest5.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest6.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest7.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest8.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest9.com,Netflix
  - DOMAIN-SUFFIX,nflxext.com,Netflix
  - DOMAIN-SUFFIX,nflximg.com,Netflix
  - DOMAIN-SUFFIX,nflximg.net,Netflix
  - DOMAIN-SUFFIX,nflxso.net,Netflix
  - DOMAIN-SUFFIX,nflxvideo.net,Netflix
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,telegramcidr,Telegram
  - RULE-SET,tld-not-cn,国外网站
  - PROCESS-NAME,ArcGISPro.exe,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - RULE-SET,proxy,手动切换
  - MATCH,手动切换





rule-providers:
  AI:
    type: http
    behavior: classical
    url: "https://whatshub.top/rule/ai.list"
    path: ./providers/rule-AI.yaml
    interval: 86400

  Google:
    type: http
    behavior: classical
    url: "https://whatshub.top/rule/Google.list"
    path: ./providers/rule-Google.yaml
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    url: "https://whatshub.top/rule/Netflix.list"
    path: ./providers/rule-Netflix.yaml
    interval: 86400

  Paypal:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/main/Rules/Services/Paypal.list"
    path: ./providers/rule-Paypal.yaml
    interval: 86400

  Twitter:
    type: http
    behavior: classical
    url: "https://whatshub.top/rule/Twitter.list"
    path: ./providers/rule-Twitter.yaml
    interval: 86400

  Spotify:
    type: http
    behavior: classical
    url: "https://whatshub.top/rule/Spotify.list"
    path: ./providers/rule-Spotify.yaml
    interval: 86400

  Google Voice:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GoogleVoice/GoogleVoice.list"
    path: ./providers/rule-GoogleVoice.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/zhanyeye/clash-rules-lite@release/microsoft-rules.txt"
    path: ./providers/rule-microsoft.yaml
    interval: 86400

  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  youtube:
    type: http
    behavior: domain
    url: https://clashios.app/static/rules/youtube-classical-set.yaml
    path: ./ruleset/youtube.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/手动切换.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  Backlist:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/zhanyeye/clash-rules-lite@release/blacklist-rules.txt"
    path: ./providers/rule-backlist.yaml
    interval: 86400
